const ROLES = {
  ADMIN: 'ADMIN',
  DISPATCHER: 'DISPATCHER',
  DRIVER: 'DRIVER',
  MAINTENANCE: 'MAINTENANCE'
};

const STATUS = {
  VEHICLE: {
    ACTIVE: 'ACTIVE',
    MAINTENANCE: 'MAINTENANCE',
    OUT_OF_SERVICE: 'OUT_OF_SERVICE'
  },
  TRIP: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  }
};

module.exports = {
  ROLES,
  STATUS
};
